
package com.example.soapclient.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UbicaPlusWS", targetNamespace = "http://ubicaplus.webservice.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UbicaPlusWS {


    /**
     * 
     * @param parametrosUbica
     * @return
     *     returns com.example.soapclient.ws.String
     */
    @WebMethod
    @WebResult(name = "consultaUbicaPlusReturn", partName = "consultaUbicaPlusReturn")
    public String consultaUbicaPlus(
        @WebParam(name = "parametrosUbica", partName = "parametrosUbica")
        ParametrosUbicaPlusDTO parametrosUbica);

}
